project:
  type: website

website:
  title: "Research Methods in Product Design"
  sidebar:
    style: "floating"
    search: true
    contents: auto
     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

